[tool.poetry]
name = "discord-engineer-bot"
version = "0.1.0a0"
description = "A small Discord bot with some games and utilities."
authors = ["router97"]
license = "MIT"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.12"
"discord.py" = "^2.3.2"
asyncpg = "^0.29.0"
python-dotenv = "^1.0.1"
langcodes = "^3.4.0"
googletrans = "^3.0.0"
faker = "^25.8.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
